// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fmessages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fmessages_2eproto;
class Location;
struct LocationDefaultTypeInternal;
extern LocationDefaultTypeInternal _Location_default_instance_;
class OneToAll;
struct OneToAllDefaultTypeInternal;
extern OneToAllDefaultTypeInternal _OneToAll_default_instance_;
class OneToOne;
struct OneToOneDefaultTypeInternal;
extern OneToOneDefaultTypeInternal _OneToOne_default_instance_;
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Walk;
struct WalkDefaultTypeInternal;
extern WalkDefaultTypeInternal _Walk_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Location* Arena::CreateMaybeMessage<::Location>(Arena*);
template<> ::OneToAll* Arena::CreateMaybeMessage<::OneToAll>(Arena*);
template<> ::OneToOne* Arena::CreateMaybeMessage<::OneToOne>(Arena*);
template<> ::Request* Arena::CreateMaybeMessage<::Request>(Arena*);
template<> ::Response* Arena::CreateMaybeMessage<::Response>(Arena*);
template<> ::Walk* Arena::CreateMaybeMessage<::Walk>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Response_Status : int {
  Response_Status_OK = 0,
  Response_Status_ERROR = 1,
  Response_Status_Response_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Response_Status_Response_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Response_Status_IsValid(int value);
constexpr Response_Status Response_Status_Status_MIN = Response_Status_OK;
constexpr Response_Status Response_Status_Status_MAX = Response_Status_ERROR;
constexpr int Response_Status_Status_ARRAYSIZE = Response_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Status_descriptor();
template<typename T>
inline const std::string& Response_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Response_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Response_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Response_Status_descriptor(), enum_t_value);
}
inline bool Response_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Response_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Response_Status>(
    Response_Status_descriptor(), name, value);
}
// ===================================================================

class Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() override;
  explicit PROTOBUF_CONSTEXPR Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *internal_default_instance();
  }
  enum MsgCase {
    kWalk = 1,
    kOneToOne = 2,
    kOneToAll = 3,
    MSG_NOT_SET = 0,
  };

  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Request& from) {
    Request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWalkFieldNumber = 1,
    kOneToOneFieldNumber = 2,
    kOneToAllFieldNumber = 3,
  };
  // .Walk walk = 1;
  bool has_walk() const;
  private:
  bool _internal_has_walk() const;
  public:
  void clear_walk();
  const ::Walk& walk() const;
  PROTOBUF_NODISCARD ::Walk* release_walk();
  ::Walk* mutable_walk();
  void set_allocated_walk(::Walk* walk);
  private:
  const ::Walk& _internal_walk() const;
  ::Walk* _internal_mutable_walk();
  public:
  void unsafe_arena_set_allocated_walk(
      ::Walk* walk);
  ::Walk* unsafe_arena_release_walk();

  // .OneToOne oneToOne = 2;
  bool has_onetoone() const;
  private:
  bool _internal_has_onetoone() const;
  public:
  void clear_onetoone();
  const ::OneToOne& onetoone() const;
  PROTOBUF_NODISCARD ::OneToOne* release_onetoone();
  ::OneToOne* mutable_onetoone();
  void set_allocated_onetoone(::OneToOne* onetoone);
  private:
  const ::OneToOne& _internal_onetoone() const;
  ::OneToOne* _internal_mutable_onetoone();
  public:
  void unsafe_arena_set_allocated_onetoone(
      ::OneToOne* onetoone);
  ::OneToOne* unsafe_arena_release_onetoone();

  // .OneToAll oneToAll = 3;
  bool has_onetoall() const;
  private:
  bool _internal_has_onetoall() const;
  public:
  void clear_onetoall();
  const ::OneToAll& onetoall() const;
  PROTOBUF_NODISCARD ::OneToAll* release_onetoall();
  ::OneToAll* mutable_onetoall();
  void set_allocated_onetoall(::OneToAll* onetoall);
  private:
  const ::OneToAll& _internal_onetoall() const;
  ::OneToAll* _internal_mutable_onetoall();
  public:
  void unsafe_arena_set_allocated_onetoall(
      ::OneToAll* onetoall);
  ::OneToAll* unsafe_arena_release_onetoall();

  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:Request)
 private:
  class _Internal;
  void set_has_walk();
  void set_has_onetoone();
  void set_has_onetoall();

  inline bool has_msg() const;
  inline void clear_has_msg();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union MsgUnion {
      constexpr MsgUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::Walk* walk_;
      ::OneToOne* onetoone_;
      ::OneToAll* onetoall_;
    } msg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Walk final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Walk) */ {
 public:
  inline Walk() : Walk(nullptr) {}
  ~Walk() override;
  explicit PROTOBUF_CONSTEXPR Walk(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Walk(const Walk& from);
  Walk(Walk&& from) noexcept
    : Walk() {
    *this = ::std::move(from);
  }

  inline Walk& operator=(const Walk& from) {
    CopyFrom(from);
    return *this;
  }
  inline Walk& operator=(Walk&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Walk& default_instance() {
    return *internal_default_instance();
  }
  static inline const Walk* internal_default_instance() {
    return reinterpret_cast<const Walk*>(
               &_Walk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Walk& a, Walk& b) {
    a.Swap(&b);
  }
  inline void Swap(Walk* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Walk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Walk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Walk>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Walk& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Walk& from) {
    Walk::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Walk* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Walk";
  }
  protected:
  explicit Walk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocationsFieldNumber = 1,
    kLengthsFieldNumber = 2,
  };
  // repeated .Location locations = 1;
  int locations_size() const;
  private:
  int _internal_locations_size() const;
  public:
  void clear_locations();
  ::Location* mutable_locations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Location >*
      mutable_locations();
  private:
  const ::Location& _internal_locations(int index) const;
  ::Location* _internal_add_locations();
  public:
  const ::Location& locations(int index) const;
  ::Location* add_locations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Location >&
      locations() const;

  // repeated uint32 lengths = 2;
  int lengths_size() const;
  private:
  int _internal_lengths_size() const;
  public:
  void clear_lengths();
  private:
  uint32_t _internal_lengths(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_lengths() const;
  void _internal_add_lengths(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_lengths();
  public:
  uint32_t lengths(int index) const;
  void set_lengths(int index, uint32_t value);
  void add_lengths(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      lengths() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_lengths();

  // @@protoc_insertion_point(class_scope:Walk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Location > locations_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > lengths_;
    mutable std::atomic<int> _lengths_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class OneToOne final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:OneToOne) */ {
 public:
  inline OneToOne() : OneToOne(nullptr) {}
  ~OneToOne() override;
  explicit PROTOBUF_CONSTEXPR OneToOne(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OneToOne(const OneToOne& from);
  OneToOne(OneToOne&& from) noexcept
    : OneToOne() {
    *this = ::std::move(from);
  }

  inline OneToOne& operator=(const OneToOne& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneToOne& operator=(OneToOne&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneToOne& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneToOne* internal_default_instance() {
    return reinterpret_cast<const OneToOne*>(
               &_OneToOne_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OneToOne& a, OneToOne& b) {
    a.Swap(&b);
  }
  inline void Swap(OneToOne* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneToOne* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OneToOne* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OneToOne>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OneToOne& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OneToOne& from) {
    OneToOne::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneToOne* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OneToOne";
  }
  protected:
  explicit OneToOne(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOriginFieldNumber = 1,
    kDestinationFieldNumber = 2,
  };
  // .Location origin = 1;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::Location& origin() const;
  PROTOBUF_NODISCARD ::Location* release_origin();
  ::Location* mutable_origin();
  void set_allocated_origin(::Location* origin);
  private:
  const ::Location& _internal_origin() const;
  ::Location* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::Location* origin);
  ::Location* unsafe_arena_release_origin();

  // .Location destination = 2;
  bool has_destination() const;
  private:
  bool _internal_has_destination() const;
  public:
  void clear_destination();
  const ::Location& destination() const;
  PROTOBUF_NODISCARD ::Location* release_destination();
  ::Location* mutable_destination();
  void set_allocated_destination(::Location* destination);
  private:
  const ::Location& _internal_destination() const;
  ::Location* _internal_mutable_destination();
  public:
  void unsafe_arena_set_allocated_destination(
      ::Location* destination);
  ::Location* unsafe_arena_release_destination();

  // @@protoc_insertion_point(class_scope:OneToOne)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Location* origin_;
    ::Location* destination_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class OneToAll final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:OneToAll) */ {
 public:
  inline OneToAll() : OneToAll(nullptr) {}
  ~OneToAll() override;
  explicit PROTOBUF_CONSTEXPR OneToAll(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OneToAll(const OneToAll& from);
  OneToAll(OneToAll&& from) noexcept
    : OneToAll() {
    *this = ::std::move(from);
  }

  inline OneToAll& operator=(const OneToAll& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneToAll& operator=(OneToAll&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneToAll& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneToAll* internal_default_instance() {
    return reinterpret_cast<const OneToAll*>(
               &_OneToAll_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(OneToAll& a, OneToAll& b) {
    a.Swap(&b);
  }
  inline void Swap(OneToAll* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneToAll* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OneToAll* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OneToAll>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OneToAll& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OneToAll& from) {
    OneToAll::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneToAll* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "OneToAll";
  }
  protected:
  explicit OneToAll(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOriginFieldNumber = 1,
  };
  // .Location origin = 1;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::Location& origin() const;
  PROTOBUF_NODISCARD ::Location* release_origin();
  ::Location* mutable_origin();
  void set_allocated_origin(::Location* origin);
  private:
  const ::Location& _internal_origin() const;
  ::Location* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::Location* origin);
  ::Location* unsafe_arena_release_origin();

  // @@protoc_insertion_point(class_scope:OneToAll)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Location* origin_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Location final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Location) */ {
 public:
  inline Location() : Location(nullptr) {}
  ~Location() override;
  explicit PROTOBUF_CONSTEXPR Location(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Location(const Location& from);
  Location(Location&& from) noexcept
    : Location() {
    *this = ::std::move(from);
  }

  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline Location& operator=(Location&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Location& default_instance() {
    return *internal_default_instance();
  }
  static inline const Location* internal_default_instance() {
    return reinterpret_cast<const Location*>(
               &_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Location& a, Location& b) {
    a.Swap(&b);
  }
  inline void Swap(Location* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Location* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Location* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Location>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Location& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Location& from) {
    Location::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Location* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Location";
  }
  protected:
  explicit Location(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 2;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Location)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t x_;
    int32_t y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response& from) {
    Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Response_Status Status;
  static constexpr Status OK =
    Response_Status_OK;
  static constexpr Status ERROR =
    Response_Status_ERROR;
  static inline bool Status_IsValid(int value) {
    return Response_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    Response_Status_Status_MIN;
  static constexpr Status Status_MAX =
    Response_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    Response_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return Response_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return Response_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return Response_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kErrMsgFieldNumber = 2,
    kShortestPathLengthFieldNumber = 3,
    kTotalLengthFieldNumber = 4,
    kStatusFieldNumber = 1,
  };
  // string errMsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // uint64 shortest_path_length = 3;
  void clear_shortest_path_length();
  uint64_t shortest_path_length() const;
  void set_shortest_path_length(uint64_t value);
  private:
  uint64_t _internal_shortest_path_length() const;
  void _internal_set_shortest_path_length(uint64_t value);
  public:

  // uint64 total_length = 4;
  void clear_total_length();
  uint64_t total_length() const;
  void set_total_length(uint64_t value);
  private:
  uint64_t _internal_total_length() const;
  void _internal_set_total_length(uint64_t value);
  public:

  // .Response.Status status = 1;
  void clear_status();
  ::Response_Status status() const;
  void set_status(::Response_Status value);
  private:
  ::Response_Status _internal_status() const;
  void _internal_set_status(::Response_Status value);
  public:

  // @@protoc_insertion_point(class_scope:Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
    uint64_t shortest_path_length_;
    uint64_t total_length_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// .Walk walk = 1;
inline bool Request::_internal_has_walk() const {
  return msg_case() == kWalk;
}
inline bool Request::has_walk() const {
  return _internal_has_walk();
}
inline void Request::set_has_walk() {
  _impl_._oneof_case_[0] = kWalk;
}
inline void Request::clear_walk() {
  if (_internal_has_walk()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.msg_.walk_;
    }
    clear_has_msg();
  }
}
inline ::Walk* Request::release_walk() {
  // @@protoc_insertion_point(field_release:Request.walk)
  if (_internal_has_walk()) {
    clear_has_msg();
    ::Walk* temp = _impl_.msg_.walk_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.msg_.walk_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Walk& Request::_internal_walk() const {
  return _internal_has_walk()
      ? *_impl_.msg_.walk_
      : reinterpret_cast< ::Walk&>(::_Walk_default_instance_);
}
inline const ::Walk& Request::walk() const {
  // @@protoc_insertion_point(field_get:Request.walk)
  return _internal_walk();
}
inline ::Walk* Request::unsafe_arena_release_walk() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Request.walk)
  if (_internal_has_walk()) {
    clear_has_msg();
    ::Walk* temp = _impl_.msg_.walk_;
    _impl_.msg_.walk_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_walk(::Walk* walk) {
  clear_msg();
  if (walk) {
    set_has_walk();
    _impl_.msg_.walk_ = walk;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Request.walk)
}
inline ::Walk* Request::_internal_mutable_walk() {
  if (!_internal_has_walk()) {
    clear_msg();
    set_has_walk();
    _impl_.msg_.walk_ = CreateMaybeMessage< ::Walk >(GetArenaForAllocation());
  }
  return _impl_.msg_.walk_;
}
inline ::Walk* Request::mutable_walk() {
  ::Walk* _msg = _internal_mutable_walk();
  // @@protoc_insertion_point(field_mutable:Request.walk)
  return _msg;
}

// .OneToOne oneToOne = 2;
inline bool Request::_internal_has_onetoone() const {
  return msg_case() == kOneToOne;
}
inline bool Request::has_onetoone() const {
  return _internal_has_onetoone();
}
inline void Request::set_has_onetoone() {
  _impl_._oneof_case_[0] = kOneToOne;
}
inline void Request::clear_onetoone() {
  if (_internal_has_onetoone()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.msg_.onetoone_;
    }
    clear_has_msg();
  }
}
inline ::OneToOne* Request::release_onetoone() {
  // @@protoc_insertion_point(field_release:Request.oneToOne)
  if (_internal_has_onetoone()) {
    clear_has_msg();
    ::OneToOne* temp = _impl_.msg_.onetoone_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.msg_.onetoone_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::OneToOne& Request::_internal_onetoone() const {
  return _internal_has_onetoone()
      ? *_impl_.msg_.onetoone_
      : reinterpret_cast< ::OneToOne&>(::_OneToOne_default_instance_);
}
inline const ::OneToOne& Request::onetoone() const {
  // @@protoc_insertion_point(field_get:Request.oneToOne)
  return _internal_onetoone();
}
inline ::OneToOne* Request::unsafe_arena_release_onetoone() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Request.oneToOne)
  if (_internal_has_onetoone()) {
    clear_has_msg();
    ::OneToOne* temp = _impl_.msg_.onetoone_;
    _impl_.msg_.onetoone_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_onetoone(::OneToOne* onetoone) {
  clear_msg();
  if (onetoone) {
    set_has_onetoone();
    _impl_.msg_.onetoone_ = onetoone;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Request.oneToOne)
}
inline ::OneToOne* Request::_internal_mutable_onetoone() {
  if (!_internal_has_onetoone()) {
    clear_msg();
    set_has_onetoone();
    _impl_.msg_.onetoone_ = CreateMaybeMessage< ::OneToOne >(GetArenaForAllocation());
  }
  return _impl_.msg_.onetoone_;
}
inline ::OneToOne* Request::mutable_onetoone() {
  ::OneToOne* _msg = _internal_mutable_onetoone();
  // @@protoc_insertion_point(field_mutable:Request.oneToOne)
  return _msg;
}

// .OneToAll oneToAll = 3;
inline bool Request::_internal_has_onetoall() const {
  return msg_case() == kOneToAll;
}
inline bool Request::has_onetoall() const {
  return _internal_has_onetoall();
}
inline void Request::set_has_onetoall() {
  _impl_._oneof_case_[0] = kOneToAll;
}
inline void Request::clear_onetoall() {
  if (_internal_has_onetoall()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.msg_.onetoall_;
    }
    clear_has_msg();
  }
}
inline ::OneToAll* Request::release_onetoall() {
  // @@protoc_insertion_point(field_release:Request.oneToAll)
  if (_internal_has_onetoall()) {
    clear_has_msg();
    ::OneToAll* temp = _impl_.msg_.onetoall_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.msg_.onetoall_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::OneToAll& Request::_internal_onetoall() const {
  return _internal_has_onetoall()
      ? *_impl_.msg_.onetoall_
      : reinterpret_cast< ::OneToAll&>(::_OneToAll_default_instance_);
}
inline const ::OneToAll& Request::onetoall() const {
  // @@protoc_insertion_point(field_get:Request.oneToAll)
  return _internal_onetoall();
}
inline ::OneToAll* Request::unsafe_arena_release_onetoall() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Request.oneToAll)
  if (_internal_has_onetoall()) {
    clear_has_msg();
    ::OneToAll* temp = _impl_.msg_.onetoall_;
    _impl_.msg_.onetoall_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_onetoall(::OneToAll* onetoall) {
  clear_msg();
  if (onetoall) {
    set_has_onetoall();
    _impl_.msg_.onetoall_ = onetoall;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Request.oneToAll)
}
inline ::OneToAll* Request::_internal_mutable_onetoall() {
  if (!_internal_has_onetoall()) {
    clear_msg();
    set_has_onetoall();
    _impl_.msg_.onetoall_ = CreateMaybeMessage< ::OneToAll >(GetArenaForAllocation());
  }
  return _impl_.msg_.onetoall_;
}
inline ::OneToAll* Request::mutable_onetoall() {
  ::OneToAll* _msg = _internal_mutable_onetoall();
  // @@protoc_insertion_point(field_mutable:Request.oneToAll)
  return _msg;
}

inline bool Request::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void Request::clear_has_msg() {
  _impl_._oneof_case_[0] = MSG_NOT_SET;
}
inline Request::MsgCase Request::msg_case() const {
  return Request::MsgCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Walk

// repeated .Location locations = 1;
inline int Walk::_internal_locations_size() const {
  return _impl_.locations_.size();
}
inline int Walk::locations_size() const {
  return _internal_locations_size();
}
inline void Walk::clear_locations() {
  _impl_.locations_.Clear();
}
inline ::Location* Walk::mutable_locations(int index) {
  // @@protoc_insertion_point(field_mutable:Walk.locations)
  return _impl_.locations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Location >*
Walk::mutable_locations() {
  // @@protoc_insertion_point(field_mutable_list:Walk.locations)
  return &_impl_.locations_;
}
inline const ::Location& Walk::_internal_locations(int index) const {
  return _impl_.locations_.Get(index);
}
inline const ::Location& Walk::locations(int index) const {
  // @@protoc_insertion_point(field_get:Walk.locations)
  return _internal_locations(index);
}
inline ::Location* Walk::_internal_add_locations() {
  return _impl_.locations_.Add();
}
inline ::Location* Walk::add_locations() {
  ::Location* _add = _internal_add_locations();
  // @@protoc_insertion_point(field_add:Walk.locations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Location >&
Walk::locations() const {
  // @@protoc_insertion_point(field_list:Walk.locations)
  return _impl_.locations_;
}

// repeated uint32 lengths = 2;
inline int Walk::_internal_lengths_size() const {
  return _impl_.lengths_.size();
}
inline int Walk::lengths_size() const {
  return _internal_lengths_size();
}
inline void Walk::clear_lengths() {
  _impl_.lengths_.Clear();
}
inline uint32_t Walk::_internal_lengths(int index) const {
  return _impl_.lengths_.Get(index);
}
inline uint32_t Walk::lengths(int index) const {
  // @@protoc_insertion_point(field_get:Walk.lengths)
  return _internal_lengths(index);
}
inline void Walk::set_lengths(int index, uint32_t value) {
  _impl_.lengths_.Set(index, value);
  // @@protoc_insertion_point(field_set:Walk.lengths)
}
inline void Walk::_internal_add_lengths(uint32_t value) {
  _impl_.lengths_.Add(value);
}
inline void Walk::add_lengths(uint32_t value) {
  _internal_add_lengths(value);
  // @@protoc_insertion_point(field_add:Walk.lengths)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Walk::_internal_lengths() const {
  return _impl_.lengths_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Walk::lengths() const {
  // @@protoc_insertion_point(field_list:Walk.lengths)
  return _internal_lengths();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Walk::_internal_mutable_lengths() {
  return &_impl_.lengths_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Walk::mutable_lengths() {
  // @@protoc_insertion_point(field_mutable_list:Walk.lengths)
  return _internal_mutable_lengths();
}

// -------------------------------------------------------------------

// OneToOne

// .Location origin = 1;
inline bool OneToOne::_internal_has_origin() const {
  return this != internal_default_instance() && _impl_.origin_ != nullptr;
}
inline bool OneToOne::has_origin() const {
  return _internal_has_origin();
}
inline void OneToOne::clear_origin() {
  if (GetArenaForAllocation() == nullptr && _impl_.origin_ != nullptr) {
    delete _impl_.origin_;
  }
  _impl_.origin_ = nullptr;
}
inline const ::Location& OneToOne::_internal_origin() const {
  const ::Location* p = _impl_.origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::Location&>(
      ::_Location_default_instance_);
}
inline const ::Location& OneToOne::origin() const {
  // @@protoc_insertion_point(field_get:OneToOne.origin)
  return _internal_origin();
}
inline void OneToOne::unsafe_arena_set_allocated_origin(
    ::Location* origin) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.origin_);
  }
  _impl_.origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OneToOne.origin)
}
inline ::Location* OneToOne::release_origin() {
  
  ::Location* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Location* OneToOne::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:OneToOne.origin)
  
  ::Location* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
  return temp;
}
inline ::Location* OneToOne::_internal_mutable_origin() {
  
  if (_impl_.origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::Location>(GetArenaForAllocation());
    _impl_.origin_ = p;
  }
  return _impl_.origin_;
}
inline ::Location* OneToOne::mutable_origin() {
  ::Location* _msg = _internal_mutable_origin();
  // @@protoc_insertion_point(field_mutable:OneToOne.origin)
  return _msg;
}
inline void OneToOne::set_allocated_origin(::Location* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.origin_;
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(origin);
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:OneToOne.origin)
}

// .Location destination = 2;
inline bool OneToOne::_internal_has_destination() const {
  return this != internal_default_instance() && _impl_.destination_ != nullptr;
}
inline bool OneToOne::has_destination() const {
  return _internal_has_destination();
}
inline void OneToOne::clear_destination() {
  if (GetArenaForAllocation() == nullptr && _impl_.destination_ != nullptr) {
    delete _impl_.destination_;
  }
  _impl_.destination_ = nullptr;
}
inline const ::Location& OneToOne::_internal_destination() const {
  const ::Location* p = _impl_.destination_;
  return p != nullptr ? *p : reinterpret_cast<const ::Location&>(
      ::_Location_default_instance_);
}
inline const ::Location& OneToOne::destination() const {
  // @@protoc_insertion_point(field_get:OneToOne.destination)
  return _internal_destination();
}
inline void OneToOne::unsafe_arena_set_allocated_destination(
    ::Location* destination) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.destination_);
  }
  _impl_.destination_ = destination;
  if (destination) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OneToOne.destination)
}
inline ::Location* OneToOne::release_destination() {
  
  ::Location* temp = _impl_.destination_;
  _impl_.destination_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Location* OneToOne::unsafe_arena_release_destination() {
  // @@protoc_insertion_point(field_release:OneToOne.destination)
  
  ::Location* temp = _impl_.destination_;
  _impl_.destination_ = nullptr;
  return temp;
}
inline ::Location* OneToOne::_internal_mutable_destination() {
  
  if (_impl_.destination_ == nullptr) {
    auto* p = CreateMaybeMessage<::Location>(GetArenaForAllocation());
    _impl_.destination_ = p;
  }
  return _impl_.destination_;
}
inline ::Location* OneToOne::mutable_destination() {
  ::Location* _msg = _internal_mutable_destination();
  // @@protoc_insertion_point(field_mutable:OneToOne.destination)
  return _msg;
}
inline void OneToOne::set_allocated_destination(::Location* destination) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.destination_;
  }
  if (destination) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(destination);
    if (message_arena != submessage_arena) {
      destination = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.destination_ = destination;
  // @@protoc_insertion_point(field_set_allocated:OneToOne.destination)
}

// -------------------------------------------------------------------

// OneToAll

// .Location origin = 1;
inline bool OneToAll::_internal_has_origin() const {
  return this != internal_default_instance() && _impl_.origin_ != nullptr;
}
inline bool OneToAll::has_origin() const {
  return _internal_has_origin();
}
inline void OneToAll::clear_origin() {
  if (GetArenaForAllocation() == nullptr && _impl_.origin_ != nullptr) {
    delete _impl_.origin_;
  }
  _impl_.origin_ = nullptr;
}
inline const ::Location& OneToAll::_internal_origin() const {
  const ::Location* p = _impl_.origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::Location&>(
      ::_Location_default_instance_);
}
inline const ::Location& OneToAll::origin() const {
  // @@protoc_insertion_point(field_get:OneToAll.origin)
  return _internal_origin();
}
inline void OneToAll::unsafe_arena_set_allocated_origin(
    ::Location* origin) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.origin_);
  }
  _impl_.origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:OneToAll.origin)
}
inline ::Location* OneToAll::release_origin() {
  
  ::Location* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Location* OneToAll::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:OneToAll.origin)
  
  ::Location* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
  return temp;
}
inline ::Location* OneToAll::_internal_mutable_origin() {
  
  if (_impl_.origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::Location>(GetArenaForAllocation());
    _impl_.origin_ = p;
  }
  return _impl_.origin_;
}
inline ::Location* OneToAll::mutable_origin() {
  ::Location* _msg = _internal_mutable_origin();
  // @@protoc_insertion_point(field_mutable:OneToAll.origin)
  return _msg;
}
inline void OneToAll::set_allocated_origin(::Location* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.origin_;
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(origin);
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:OneToAll.origin)
}

// -------------------------------------------------------------------

// Location

// int32 x = 1;
inline void Location::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t Location::_internal_x() const {
  return _impl_.x_;
}
inline int32_t Location::x() const {
  // @@protoc_insertion_point(field_get:Location.x)
  return _internal_x();
}
inline void Location::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void Location::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Location.x)
}

// int32 y = 2;
inline void Location::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t Location::_internal_y() const {
  return _impl_.y_;
}
inline int32_t Location::y() const {
  // @@protoc_insertion_point(field_get:Location.y)
  return _internal_y();
}
inline void Location::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void Location::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Location.y)
}

// -------------------------------------------------------------------

// Response

// .Response.Status status = 1;
inline void Response::clear_status() {
  _impl_.status_ = 0;
}
inline ::Response_Status Response::_internal_status() const {
  return static_cast< ::Response_Status >(_impl_.status_);
}
inline ::Response_Status Response::status() const {
  // @@protoc_insertion_point(field_get:Response.status)
  return _internal_status();
}
inline void Response::_internal_set_status(::Response_Status value) {
  
  _impl_.status_ = value;
}
inline void Response::set_status(::Response_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:Response.status)
}

// string errMsg = 2;
inline void Response::clear_errmsg() {
  _impl_.errmsg_.ClearToEmpty();
}
inline const std::string& Response::errmsg() const {
  // @@protoc_insertion_point(field_get:Response.errMsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Response::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errmsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Response.errMsg)
}
inline std::string* Response::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:Response.errMsg)
  return _s;
}
inline const std::string& Response::_internal_errmsg() const {
  return _impl_.errmsg_.Get();
}
inline void Response::_internal_set_errmsg(const std::string& value) {
  
  _impl_.errmsg_.Set(value, GetArenaForAllocation());
}
inline std::string* Response::_internal_mutable_errmsg() {
  
  return _impl_.errmsg_.Mutable(GetArenaForAllocation());
}
inline std::string* Response::release_errmsg() {
  // @@protoc_insertion_point(field_release:Response.errMsg)
  return _impl_.errmsg_.Release();
}
inline void Response::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  _impl_.errmsg_.SetAllocated(errmsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errmsg_.IsDefault()) {
    _impl_.errmsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Response.errMsg)
}

// uint64 shortest_path_length = 3;
inline void Response::clear_shortest_path_length() {
  _impl_.shortest_path_length_ = uint64_t{0u};
}
inline uint64_t Response::_internal_shortest_path_length() const {
  return _impl_.shortest_path_length_;
}
inline uint64_t Response::shortest_path_length() const {
  // @@protoc_insertion_point(field_get:Response.shortest_path_length)
  return _internal_shortest_path_length();
}
inline void Response::_internal_set_shortest_path_length(uint64_t value) {
  
  _impl_.shortest_path_length_ = value;
}
inline void Response::set_shortest_path_length(uint64_t value) {
  _internal_set_shortest_path_length(value);
  // @@protoc_insertion_point(field_set:Response.shortest_path_length)
}

// uint64 total_length = 4;
inline void Response::clear_total_length() {
  _impl_.total_length_ = uint64_t{0u};
}
inline uint64_t Response::_internal_total_length() const {
  return _impl_.total_length_;
}
inline uint64_t Response::total_length() const {
  // @@protoc_insertion_point(field_get:Response.total_length)
  return _internal_total_length();
}
inline void Response::_internal_set_total_length(uint64_t value) {
  
  _impl_.total_length_ = value;
}
inline void Response::set_total_length(uint64_t value) {
  _internal_set_total_length(value);
  // @@protoc_insertion_point(field_set:Response.total_length)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Response_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Response_Status>() {
  return ::Response_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fmessages_2eproto
